import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/common/theme-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NicAhorro",
  description: "Generated by create next app",
  applicationName: 'NicAhorro',
  authors: [{ name: 'Gabriel Avilés', url: 'https://github.com/gabo592' }],
  generator: 'Next.js',
  keywords: ['nic', 'ahorro', 'web', 'aplicación'],
  referrer: 'no-referrer-when-downgrade',
  creator: 'Gabriel Avilés',
  publisher: 'Vercel'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
